apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    app: whalesay
  name: whalesay
spec:
  backoffLimit: 6
  completions: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: whalesay
    spec:
      containers:
      - args:
        - kubectl
        - run
        image: docker/whalesay
        name: whalesay
        command: ["cowsay"]
        args: ["cowsay I am going to ace CKAD!"]
        resources: {}
      restartPolicy: Never
status: {}
