apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  labels:
    job: newJob
  name: newJob
spec:
  backoffLimit: 6
  completions: 10
  template:
    metadata:
      creationTimestamp: null
      labels:
        job: newJob
    spec:
      containers:
      - args:
        - kubectl
        - run
        image: docker/whalesay
        name: newJob
        command: ["cowsay"]
        args: ["cowsay I am going to ace CKAD!"]
        resources: {}
      restartPolicy: Never
status: {}
