apiVersion: v1
kind: PersistentVolume
metadata:
  name: custom-volume
spec:
  capacity:
    storage: 50MiB
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
