apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: 2020-02-19T03:18:21Z
  generation: 2
  labels:
    name: busybox-pod
  name: rs-d33393
  namespace: default
  resourceVersion: "6735"
  selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/rs-d33393
  uid: 7b808795-52c6-11ea-a160-0242ac110008
spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 4
  observedGeneration: 2
  replicas: 4
